# Generated by Django 4.0.1 on 2022-02-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0003_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='User',
            new_name='user',
        ),
    ]
