# Generated by Django 4.0.1 on 2022-02-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0004_rename_user_homework_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due',
            field=models.DateField(verbose_name=['%Y-%m-%d']),
        ),
    ]
