# Generated by Django 4.0.1 on 2022-02-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0005_alter_homework_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due',
            field=models.DateTimeField(default=False),
        ),
    ]
