# Generated by Django 4.0.1 on 2022-02-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0009_alter_homework_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due',
            field=models.DateTimeField(verbose_name='2022-02-09 14:54:44 +00:00'),
        ),
    ]
